services:
  jupyter:
    container_name: plotly_test
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"